version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: flask
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://root:root@mysql/db

volumes:
  db_data: