name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: 
            pip install -r requirements.txt
            pip install pytest pylint
        

      # Add your tests or build commands here
      # For example, running pytest
      - name: Run tests
        run: 
            pytest tests/
            pylint *.py tests/*.py forms/*.py

      - name: Send Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

